### ISSUE TITLE
最新版是把Then和For都改成Pipe了吗

### ISSUE THREAD

**Issue by ioer2008** [zmjack/NStandard#4]

**Comment by zmjack** [comment]
是的。

`Then` / `For` 方法创建比较早，命名上没有太多考虑。

为了使其更加语义化，现将它们重命名为 `Pipe`。

--- 

`For` 对标的是 **F#** 中的 **Pipe operator** `|>`。

通过此运算符，可采用灵活的方式建立函数的“管道”。 流水线处理可让函数调用链接在一起形成连续的操作：

例如，**F#** 中将 **string** 转换为 **Base64** 的例子：

```F#
// string -> byte[] -> string
"Hello"
    |> Encoding.UTF8.GetBytes
    |> Convert.ToBase64String
```

**C#** 对标写法：

```C#
"Hello"
    .Pipe(Encoding.UTF8.GetBytes)
    .Pipe(Convert.ToBase64String);
```

---

接上面的例子，说明 `Then` / `For` 合并为 `Pipe` 的原因。

例如，我们希望在转换过程中插入其他操作（`Console.WriteLine`）：

```C#
"Hello"
    .Pipe(Encoding.UTF8.GetBytes)
    .Pipe(Console.WriteLine)
    .Pipe(Convert.ToBase64String)
    .Pipe(Console.WriteLine);
```

再看旧式写法，需要区分 `Then` / `For`：

```C#
"Hello"
    .For(Encoding.UTF8.GetBytes)
    .Then(x => Console.WriteLine(x))
    .For(Convert.ToBase64String)
    .Then(x => Console.WriteLine(x));
```

可以看出，它们都是连续操作中的一环，区别在于 **函数参数** 是否包含 **返回值**（`void` / `any`）。

所以，将它们合并为单一函数 `Pipe` 调用会更简单。

另一原因是，代码更整洁了！（`For` = 3 字符，`Then` = 4 字符）😆。

---

以上，感谢关注。

**Comment by ioer2008** [comment]
主要是更新日志里面没有找到说明,感谢解答
